JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Models/ErrorViewModel.cs
using System;

namespace WebApplicationJuanJose.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Models/Registro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationJuanJose.Models
{
    public class Registro
    {
        [Key]
        public int IdRegistro { get; set; }
        [DisplayName("Foto")]
        public byte img { get; set; }
        [DisplayName("Documento")]
        [StringLength(20)]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Por favor ingrese el documento")]
        public string documento { get; set; }

        [DisplayName("Nombres")]
        [StringLength(30)]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Por favor ingrese mínimo un nombre")]
        public string Nombres { get; set; }

        [DisplayName("Apellidos")]
        [StringLength(30)]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Por favor ingrese mínimo un apellido")]
        public string Apellidos { get; set; }

        [DisplayName("Fecha nacimiento")]
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage = "Debe ingresar una fecha de nacimiento")]
        [DisplayFormat(DataFormatString = ("{0:dd-MM-yyyy}"))]
        public DateTime FechaNacimiento { get; set; }

        [DisplayName("Dirección")]
        [StringLength(100)]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Por favor ingrese una dirección")]
        public string Direccion { get; set; }

        [DisplayName("Celular")]
        [StringLength(15)]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Por favor ingrese un número de celular")]
        public string Celular { get; set; }

        [DisplayName("Género")]
        [StringLength(1)]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Género requerido")]
        public string Genero { get; set; }

        [DisplayName("Deporte")]
        [StringLength(30)]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Por favor ingrese un deporte")]
        public string Deporte { get; set; }


        [DisplayName("Trabaja")]
        [StringLength(2)]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Por favor ingrese un deporte")]
        public string Trabaja { get; set; }

        [DisplayName("Salario")]
        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "Por favor ingrese su salario")]
        public string Salario { get; set; }

        [DisplayName("Estado")]
        [StringLength(1)]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Estado requerido")]
        public string Estado { get; set; }
    }
}

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationJuanJose.Models;

namespace WebApplicationJuanJose.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Controllers/RegistroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationJuanJose.Data;
using WebApplicationJuanJose.Models;

namespace WebApplicationJuanJose.Controllers
{
    public class RegistroesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RegistroesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Registroes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Registro.ToListAsync());
        }

        // GET: Registroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registro
                .FirstOrDefaultAsync(m => m.IdRegistro == id);
            if (registro == null)
            {
                return NotFound();
            }

            return View(registro);
        }

        // GET: Registroes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Registroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRegistro,img,documento,Nombres,Apellidos,FechaNacimiento,Direccion,Celular,Genero,Deporte,Trabaja,Salario,Estado")] Registro registro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(registro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(registro);
        }

        // GET: Registroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registro.FindAsync(id);
            if (registro == null)
            {
                return NotFound();
            }
            return View(registro);
        }

        // POST: Registroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRegistro,img,documento,Nombres,Apellidos,FechaNacimiento,Direccion,Celular,Genero,Deporte,Trabaja,Salario,Estado")] Registro registro)
        {
            if (id != registro.IdRegistro)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegistroExists(registro.IdRegistro))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(registro);
        }

        // GET: Registroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registro
                .FirstOrDefaultAsync(m => m.IdRegistro == id);
            if (registro == null)
            {
                return NotFound();
            }

            return View(registro);
        }

        // POST: Registroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var registro = await _context.Registro.FindAsync(id);
            _context.Registro.Remove(registro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegistroExists(int id)
        {
            return _context.Registro.Any(e => e.IdRegistro == id);
        }
    }
}

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 style="color:blue;" class="display-4">Bienvenidos</h1>
    <p>Hola criaturitas del señor</p>
</div>

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Views/Registroes/Create.cshtml
@model WebApplicationJuanJose.Models.Registro

@{
    ViewData["Title"] = "Create";
}

<h1 style="color:forestgreen;">Datos personales</h1>


<hr />

<form asp-action="Create">

    <div class="form-group">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @*<div class="form-group">
                <label asp-for="img" class="control-label"></label>
                <input asp-for="img" class="form-control" />
                <span asp-validation-for="img" class="text-danger"></span>
            </div>*@
    </div>


    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="documento" class="control-label"></label>
                <input asp-for="documento" class="form-control" />
                <span asp-validation-for="documento" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
        </div>



        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-8">
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Deporte" class="control-label"></label>
                @*<input asp-for="Deporte" class="form-control" />*@
            <select class="custom-select" asp-for="Deporte" required>
                <option disabled>Seleccionar</option>
                <option>Baloncesto</option>
                <option>Futbol</option>
                <option>Natacion</option>
            </select>
                <span asp-validation-for="Deporte" class="text-danger"></span>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Trabaja" class="control-label"></label>
                @*<input asp-for="Trabaja" class="form-control" />*@
                <select class="custom-select" asp-for="Trabaja" required>
                    <option disabled>Seleccionar</option>
                    <option>Si</option>
                    <option>No</option>
                </select>
                <span asp-validation-for="Trabaja" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                @*<input asp-for="Estado" class="form-control" />*@
                <select class="custom-select" asp-for="Estado" required>
                    <option disabled>Seleccionar</option>
                    <option>A(Activo)</option>
                    <option>I(Inactivo)</option>
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
        </div>

    </div>
        <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-primary" />
            <a class="btn btn-danger" asp-action="Index">Cancelar</a>
        </div>
</form>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Views/Registroes/Delete.cshtml
@model WebApplicationJuanJose.Models.Registro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Registro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.img)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.documento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.documento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deporte)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deporte)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trabaja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trabaja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdRegistro" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Views/Registroes/Details.cshtml
@model WebApplicationJuanJose.Models.Registro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Registro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.img)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.documento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.documento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deporte)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deporte)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trabaja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trabaja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdRegistro">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Views/Registroes/Edit.cshtml
@model WebApplicationJuanJose.Models.Registro

@{
    ViewData["Title"] = "Edit";
}

    <h1>Edit</h1>

<h4>Registro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdRegistro" />
            <div class="form-group">
                <label asp-for="img" class="control-label"></label>
                <input asp-for="img" class="form-control" />
                <span asp-validation-for="img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="documento" class="control-label"></label>
                <input asp-for="documento" class="form-control" />
                <span asp-validation-for="documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deporte" class="control-label"></label>
                <input asp-for="Deporte" class="form-control" />
                <span asp-validation-for="Deporte" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trabaja" class="control-label"></label>
                <input asp-for="Trabaja" class="form-control" />
                <span asp-validation-for="Trabaja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Views/Registroes/Index.cshtml
@model IEnumerable<WebApplicationJuanJose.Models.Registro>

@{
    ViewData["Title"] = "Index";
}

<h1>Tabla de registros</h1>

<p>
    <a style="color:forestgreen;" asp-action="Create">Nuevo registro</a>
</p>
<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.img)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.documento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombres)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>*@
            @*<th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Celular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Deporte)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Trabaja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.img)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.documento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellidos)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>*@
            @*<td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Celular)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Deporte)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Trabaja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.IdRegistro">Editar</a> 
                <a  class="btn btn-info" asp-action="Details" asp-route-id="@item.IdRegistro">Detalle</a> 
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.IdRegistro">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

JoseFreddy/webJuanJoseLemos/WebApplicationJuanJose/WebApplicationJuanJose/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationJuanJose</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a style="font-size:30px;" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Juan José Developer </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registroes" asp-action="Index">Registro</a>
                        </li>                
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Juan José Developer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>